# Generated by Django 4.2.7 on 2023-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado_ia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField(default=0)),
                ('resultado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('senha', models.CharField(max_length=128)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('raca', models.CharField(choices=[('B', 'Branca'), ('P', 'Preta'), ('A', 'Amarela'), ('P', 'Parda'), ('I', 'Indígena')], max_length=1)),
                ('pdc', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('regiao', models.CharField(choices=[('N', 'Norte'), ('NE', 'Nordeste'), ('S', 'Sul'), ('SE', 'Suldeste'), ('CO', 'Centro-Oeste')], max_length=2)),
            ],
        ),
    ]
