# Generated by Django 4.2.7 on 2023-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='raca',
            field=models.CharField(choices=[('B', 'Branca'), ('P', 'Preta'), ('A', 'Amarela'), ('PA', 'Parda'), ('I', 'Indígena')], max_length=2),
        ),
    ]
