# Generated by Django 4.2.7 on 2023-11-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_usuario_raca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='username',
        ),
    ]
