# Generated by Django 4.2.7 on 2023-11-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_rename_senha_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
